### PR TITLE
Add -i and -t flags for compatibility

### PR DESCRIPTION
**Pull request by langemeijer**
This commit fixes issue #11

### CODE REVIEW

**Comment by briceburg** [comment]
Thanks @langemeijer I'll test. Did you happen to see our PR #12 where we update the flag handling package + code to support POSIX --flags ?

@ian-kent is this project still active? It's very awesome and I'd be glad to help if possible. :heart:

**Comment by langemeijer** [comment]
I'll do the work on top of pr #12 again once it gets merged.

Op do 23 jun. 2016 00:14 schreef Brice Burgess <notifications@github.com>:

**Comment by ian-kent** [comment]
thanks @langemeijer 

@briceburg yes, definitely! not as active as I'd have liked though 😿

**Comment by briceburg** [comment]
@ian-kent many thanks. totally understand -- it was great fun learning go for this! :)

**Pull request merged**
